Adding source
di-shykh/RssReader pull request #14
Opened 2018-04-17 12:19 UTC by di-shykh

2018-04-19 19:23 UTC, nLight commented on src/components/AddSource.vue
> +            categor:''
лучше не сокращать таким образом. `category` всего на один символ длиннее. Сокращения, если не общеупотребимые, сложно понять другим членам команды.

2018-04-19 19:26 UTC, nLight commented on src/components/AddSource.vue
> +          return art;
3 первых статьи можно вернуть следующим образом 
```js
this.source.articles.slice(0, 3);
```
это не поменяет массив, а создаст новый, элементами которого будут элементы исходного массива 3 штуки от 0-индекса

2018-04-19 19:30 UTC, nLight commented on src/components/AddSource.vue
> +          if(this.categor.trim()){
Надо стараться выдерживать отступы, либо 4 пробела, либо 2.

2018-04-19 19:31 UTC, nLight commented on src/components/Header.vue
> +    return{
отступы

2018-04-19 19:32 UTC, nLight commented on src/components/Sidebar.vue
> +        var strSourece=document.getElementById('sidebar-input').value;
🔤 strSourece -> strSource, addSourse -> addSource

2018-04-19 19:33 UTC, nLight commented on src/components/Sidebar.vue
> +      alert(sidebarWidth,sidebarFooter.clientWidth);
можно удалить

2018-04-19 19:36 UTC, nLight commented on src/store/modules/source.js
> +    findSource:(state,str)=>{
str - это я подозреваю URL? Если да, то лучше так и назвать

2018-04-19 19:39 UTC, nLight commented on src/store/modules/source.js
> +            $.ajax(str, {
можно сделать без jquery, например, как в этом совете https://stackoverflow.com/a/41009103

2018-04-19 19:41 UTC, nLight commented on src/store/modules/user.js
> +    isLogged: state => (state.user != null)
👍

2018-04-19 19:44 UTC, nLight commented on src/store/modules/userSources.js
> +            data.forEach(function(data) {
можно заменить на `map`
```js
sources = data.map(element => ({ key: element.key, source: element.val().source }))
```

2018-04-19 19:45 UTC, nLight commented on src/store/modules/userSources.js
> +            data.forEach(function(data) {
можно заменить на map

2018-04-19 19:46 UTC, nLight reviewed
Ты в каком редакторе работаешь? Надо настроить vue-prettier и eslint.

2018-04-25 20:32 UTC, nLight requested changes
Мы проведем здесь довольно много времени :) Будем постепенно улучшать и в итоге смержим! 2000 линий изменений довольно сложно просмотреть одним махом. Обычно так и бывает, что ревью происходит в несколько этапов, а то и вовсе PR закрывают и просят разбить на несколько маленьких 😅

2018-04-25 20:32 UTC, nLight commented on src/store/modules/source.js
> +      // code for IE6, IE5
Про этих ребят можно забыть :)

2018-04-25 20:32 UTC, nLight commented on src/store/modules/source.js
> +import $ from 'jquery';
jquery больше не нужен

2018-04-25 20:32 UTC, nLight commented on src/store/modules/source.js
> +    var x = xmlDoc.getElementsByTagName('channel');
Переменным лучше давать явные названия. Например здесь лучше так и назвать `channel`.
Опять же если сделать `xmlDoc.getElementsByTagName('channel')[0]` то не придется этот индекс внизу за собой везде таскать.

2018-04-25 20:32 UTC, nLight commented on src/store/modules/source.js
> +    var url = x[0].getElementsByTagName('link')[0].childNodes[0].nodeValue;
Если есть желание, можно заглянуть в `XPath` чтобы упростить разбор документа.
https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate
XPath - это язык запросов к документу. Позволяет выстроить путь до нужного значения без использования объектной модели документа напрямую.
То что ты сейчас используешь - это как раз объектная модель или Document Object Model (DOM). Суть в том, что документ представлен в виде иерархии объектов с функциями типа `getElementByTagName` и свойствами типа `childNodes`

XPath для `url` будет выглядеть примерно так `/channel/link/text()`

При большой вложенности может быть гораздо короче удобнее и понятнее

На память правила XPath запоминать не стоит можно всегда иметь под рукой что-то типа http://xmltoolbox.appspot.com/xpath_generator.html или инспектор хрома

<img width="1039" alt="screen shot 2018-04-25 at 22 20 35" src="https://user-images.githubusercontent.com/186223/39270616-e821e4b2-48d6-11e8-9e31-beba460ec6da.png">

2018-04-25 20:32 UTC, nLight commented on src/store/modules/source.js
> +    for (let j = 0; j < item.length; j++) {
я предлагаю везде использовать `let` и `const` вместо `var`.
`let` когда нужно переопределить переменную и const когда не надо. В данном случае нужно использовать `const` потому что в рамках блока цикла переменная `j` не переопределяется

2018-04-25 20:32 UTC, nLight commented on src/main.js
> +Vue.use(VueFire);
Насколько я вижу в итоге ты решила использовать firebase напрямую?

2018-04-27 08:54 UTC, di-shykh commented on src/store/modules/source.js
> +    for (let j = 0; j < item.length; j++) {
j ведь меняется в цикле с каждой итерацией?..или я не правильно понимаю переопределение переменной?

2018-04-27 11:25 UTC, di-shykh commented on src/main.js
> +Vue.use(VueFire);
Я не то чтобы решила..Просто не поняла как ее правильно использовать в моем случае. Поэтому в итоге, да не пользуюсь.

2018-05-03 20:34 UTC, nLight requested changes

2018-05-03 20:34 UTC, nLight commented on src/store/modules/source.js
> +    for (let j = 0; j < item.length; j++) {
Ты права! :)

2018-05-03 20:34 UTC, nLight commented on src/components/Reader.vue
> +    <!--<img :src="user.photoURL" width="100"> <br>-->
Закомментированный код лучше не оставлять

2018-05-03 20:34 UTC, nLight commented on src/components/AddSource.vue
> +        menu.style.left = `${this.x - 230}px`;
думаю... можно ли это сделать через [css transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) т.е. тебе тут нужно будет просто css класс менять.

2018-05-03 20:34 UTC, nLight commented on src/components/AddSource.vue
> +      if (menu) {
опять же если это убрать в трансфомацию, я присвоение класса вынести в отдельную функцию (hideMenu?) то код станет чище и понятнее, что происходит

2018-05-03 20:34 UTC, nLight commented on src/components/AddSource.vue
> +    /*const content = document.getElementById('app-content');
лучше удалять, а не комментировать.

2018-05-03 20:34 UTC, nLight commented on src/components/Article.vue
> +      return str.slice(0, start) + str.slice(end + 2);
Супер! Давай попробуем регулярные выражения `str.replace(...)` https://www.w3schools.com/jsref/jsref_replace.asp

2018-05-03 20:34 UTC, nLight commented on src/components/Article.vue
> +      return str
👍

2018-05-03 20:34 UTC, nLight commented on src/components/Article.vue
> +      <button class="btn btn-primary col-md-4 offset-md-4" @click="openInNewTab(article.link)">Visit website</button>
Можно заменить на `<a href={{article.link}} target="_blank">Visit</a>` и js не нужен

2018-05-03 20:34 UTC, nLight commented on src/components/Article.vue
> +      const icon = document.querySelector('#icon');
Посмотри, как можно в Vue управлять классами через `v-bind`
https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax

2018-05-03 20:34 UTC, nLight commented on src/components/Article.vue
> +      const icon = document.querySelector('#icon');
Точно так же можно и меню управлять.

2018-05-03 20:34 UTC, nLight commented on src/components/AddSource.vue
> +          <div v-show="show" class="menu-for-adding-source">
вместо `show` лучше использовать говорящие названия. Что-то вроде `isMenuSourceVisible` `isMenuCategoryVisible`. В JS это что-то вроде договоренности называть true/false переменные с префикса `is..`

2018-05-03 20:34 UTC, nLight commented on src/components/AddSource.vue
> +.menu-for-adding-source {
`menu-for-adding-source` и `menu-for-adding-category` одинаковые. Можно использовать базовый класс `menu` и модификаторы `menu-source` и `menu-category` соответственно. `menu` будет содержать все общие стили, а модификаторы - только различия.

2018-05-03 20:34 UTC, nLight commented on src/components/Article.vue
> +        <!--<div v-html="findImgOfArticle(article.description)" v-else class="img-thumbnail"></div>-->
Давай удалим весь мертвый код :)

2018-05-03 20:34 UTC, nLight commented on src/components/Articles.vue
> +        return source.source.articles;
может такое быть, что источника с таким именем в `this.sources` не окажется? Тогда `source` будет `undefined`  и на этой строке будет ошибка.

2018-05-03 20:34 UTC, nLight commented on src/components/Articles.vue
> +          if (item.source.category == this.categoryName) {
Всегда используй `===`  и `!==` 2 равно можно использовать только в случае сравнения с `null`
https://eslint.org/docs/rules/eqeqeq

2018-05-03 20:34 UTC, nLight commented on src/components/Articles.vue
> +        this.sources.forEach(item => {
это можно переписать через цепочку `this.sources.filter(...).reduce(...)` цепочки легче читать. Потому что когда у тебя условие в цикле не всегда сразу понятно, что происходит. В цепочках это просто поток данных. Понятно, что сперва отфильтровали, а потом изменили как надо.

2018-05-03 20:34 UTC, nLight commented on src/components/Articles.vue
> +        let art = [];
аналогично

2018-05-03 20:34 UTC, nLight commented on src/components/Articles.vue
> +      const start = str.indexOf('<img');
мне кажется нам нужна функция для удаления картинок :) Я выше уже писал.

2018-05-03 20:34 UTC, nLight commented on src/components/Articles.vue
> +    getDate(str) {
и отдельная функция для преобразования даты

2018-05-03 20:34 UTC, nLight commented on src/components/Reader.vue
> +    sidebar.style.top = `${headerHeigth}px`;
Я не понимаю, что тут происходит, потом еще вернусь

2018-05-03 20:34 UTC, nLight commented on src/components/Sidebar.vue
> +    <div class="sidebar-toggle" v-if="!showSidebar">
`showSidebar` => `isSidebarVisible` почему здесь решила использовать `v-if` а не `v-show`?

2018-05-03 20:34 UTC, nLight commented on src/store/modules/appearance.js
> +    function changeContenttSize() {
Я уверен, что это можно просто сверстать в css. Что ты тут делаешь?

2018-05-03 20:34 UTC, nLight commented on src/store/modules/source.js
> +        function findItemValue(xpath) {
👍 молодец, что вынесла helper

2018-05-03 20:34 UTC, nLight commented on src/store/modules/source.js
> +          let article = {
несмотря на то, что ты меняешь поля `article` сама переменная не переопределяется. Можно `const`.

2018-05-20 20:00 UTC, di-shykh commented on src/components/AddSource.vue
> +        menu.style.left = `${this.x - 230}px`;
Я не понимаю как мне тут поможет transform. Я так понимаю ты имеешь в виду transform: translate, но чем оно мне поможет? Можешь объяснить? У меня 2 абсолютно спозиционированные формы. Я определяю где был клик(т.е. где кнопка) и относительно нее задаю позицию для этих всплывающих форм.

2018-05-20 20:04 UTC, di-shykh commented on src/components/Article.vue
> +      const icon = document.querySelector('#icon');
Вот тут у меня проблема. Классы меняются динамически,а иконки нет(см.комментарий строка 44).Посмотри,пожалуйста,что я не так делаю.

2018-05-20 20:07 UTC, di-shykh commented on src/components/Articles.vue
> +        let art = [];
Вот тут почему-то reduce(...) у меня не работает. Буду очень признательна,если скажешь,что не так(см.комментарий строка 64)

2018-05-20 20:09 UTC, di-shykh commented on src/components/Sidebar.vue
> +    <div class="sidebar-toggle" v-if="!showSidebar">
Да,тут лучше использовать v-show,ты прав.

2018-05-20 20:20 UTC, di-shykh commented on src/store/modules/appearance.js
> +    function changeContenttSize() {
А тут у меня беда с версткой. Боковое меню(сайдбар) у меня position: fixed. Т.к. я хочу чтобы оно все время было видно и доступно. И тут у меня 2 проблемы.
Во-первых, когда сайдбар открывается или не достаточно в окне места для блока с контентом, то это все дело налазит на сайдбар.  Поэтому я пытаюсь определить ширину сайдбара, установить для контента отступ слева на это расстояние и уменьшить ширину блока с контентом,чтобы не вылазила снизу полоса прокрутки.
Во-вторых, если много блогов/источников в списке и они не помещаются все в сайдбаре,то полоса прокрутки не появляется, я просто не вижу,того,что не помещается... Как-то так.

2018-05-22 20:16 UTC, nLight commented on src/components/Articles.vue
> +        //let art = this.sources.reduce(([], item) => [...item.source.articles]); //не работает..и [].concat(item.source.articles) тоже не работает..Почему?
```js
let art = this.sources.reduce((acc, item) => acc.concat(item.source.articles), acc);
```
Для начала давай разберемся с операцией `reduce`. Прямой перевод говорит, что это уменьшение. На самом деле это больше преобразование одного множества в другое. Иногда на выходе у тебя меньше элементов, иногда больше, иногда столько же.

В данном примере мы преобразуем множество источников в большее множество статей.

`reduce` принимает 2 аргумента. Функцию редюсер и, опционально, начальное значение. Если начальное значение не задано, то первое значение массива будет использовано вместо него. Но т.к. мы почти никогда не можем гарантировать, что в массиве что-то есть задавать начальное значение лучше всегда. 

Теперь давай посмотрим на сигнатуру (обозначение) функции редюсера. Функция принимает 3 аргумента:
- аккумулятор
- текущий элемент массива
- индекс текущего элемента

```js
function reducerFunction(accumulator, currentValue, currentIndex) {
  return transformedAccumulator;
}

array.reduce(reducerFunction, initialValue);
```

Функция редюсер для каждого элемента массива возвращает значение, которое будет передано в качестве аккумулятора в редюсер вместе со _следующим_ элементом.

Получается, что у тебя есть некоторое начальное значение, которое ты на каждом шаге изменяешь и результатом выполнения всей операции будет, по сути, значение, которое вернет функция редюсер для _последнего_ элемента массива.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

Почему не работало
```js
let art = this.sources.reduce(([], item) => [...item.source.articles]);
```
`([], item) => { ... }` - означает: эй, JS! Первым аргументом придет массив, но он мне не нужен целиком мне нужны некоторые его элементы. Но конкретно здесь какие элементы не указано, поэтому первый аргумент вообще никак не будет использован.
Подробнее: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

`[...item.source.articles]` и `[].concat(item.source.articles)` не работало потому что на каждом шаге мы не добавляли статьи в аккумулятор, а возвращали стати текущего элемента. В итоге на выходе имели только статьи последнего источника.

На звонке еще поговорим про это.

2018-05-22 20:16 UTC, nLight commented on src/components/Articles.vue
> +          .reduce(([], item) => [...item.source.articles]); //if there are several sources in the category, then everything is displayed correctly. If there is only one, then art is the source object
эта штука не работает по причинам описаным ниже

2018-05-30 03:30 UTC, nLight commented on src/store/modules/appearance.js
> +    function changeContenttSize() {
Я думаю, что здесь лучше сделать без position fixed. Это решит много проблем. Попробуй сверстать сайдбар и контентную облать через flex-box, а внутри контентной области сделай overflow: scroll. Тогда можно будет через css класс зафиксировать 2 ширины сайд бара и переключать их. Тебе не нужно вычислять ширину каждый раз.

2018-05-30 13:01 UTC, nLight commented on src/components/Article.vue
> +      return [this.article.readLater ? 'fas' : 'far', 'fa-bookmark', 'fa-2x']; //иконка меняется только после повторного открытия,а не динамически.this.article.readLater и класс меняется динамически.
- пометка

2018-05-30 13:01 UTC, nLight commented on src/components/Article.vue
> +      if (source) this.$store.dispatch('userSources/saveCurrentSource', source);
Если верить людям на stackoverflow обновлять элементы в массиве есть. Я не вижу твоих промежуточных решений, конечно, но пишут, что можно через `userDb.child('sources/' + source.key + '/' + this.article.key). setValue` Как ты пробовала добраться?
https://stackoverflow.com/questions/46742426/firebase-update-array-value-or-create-new-one

2018-05-30 13:01 UTC, nLight commented on src/store/modules/userSources.js
> +          let sour = {
Лучше писать целиком `source`, а то сейчас получилось "кислый" :)

2018-06-10 07:15 UTC, di-shykh commented on src/components/Articles.vue
> +        //let art = this.sources.reduce(([], item) => [...item.source.articles]); //не работает..и [].concat(item.source.articles) тоже не работает..Почему?
Да,это нужно обсудить. Хоть убей не понимаю, почему не добавляли..я же использовала concat..т.е. я взяла пустой массив и к нему на каждом шаге добавляла массив из  item.source.articles.

2018-06-10 07:23 UTC, di-shykh commented on src/components/Article.vue
> +      return [this.article.readLater ? 'fas' : 'far', 'fa-bookmark', 'fa-2x']; //иконка меняется только после повторного открытия,а не динамически.this.article.readLater и класс меняется динамически.
???

2018-06-10 07:30 UTC, di-shykh commented on src/store/modules/userSources.js
> +          let sour = {
ok:)

2018-06-12 07:02 UTC, nLight commented on src/components/Article.vue
> +      return [this.article.readLater ? 'fas' : 'far', 'fa-bookmark', 'fa-2x']; //иконка меняется только после повторного открытия,а не динамически.this.article.readLater и класс меняется динамически.
Это я себе оставил пометку, чтобы разобраться :)

2018-06-12 20:27 UTC, nLight commented on src/components/Article.vue
> +      return [this.article.readLater ? 'fas' : 'far', 'fa-bookmark', 'fa-2x']; //иконка меняется только после повторного открытия,а не динамически.this.article.readLater и класс меняется динамически.
Как должна меняться иконка? Сейчас динамически меняется только `fas` и `far`. Но я вообще не вижу где эти стили объявляются.  `fa-bookmark` и `fa-2x` всегда будут подставляться.

Т.е. ты видишь, что класс поменялся на правильный, но сама иконка не поменялась?

2018-06-13 07:59 UTC, di-shykh commented on src/components/Article.vue
> +      return [this.article.readLater ? 'fas' : 'far', 'fa-bookmark', 'fa-2x']; //иконка меняется только после повторного открытия,а не динамически.this.article.readLater и класс меняется динамически.
Да, это и непонятно. Класс правильный(смотрю classObj в vue devtools), а иконка динамически не меняется. Причем когда открываю эту же статью потом, то иконка правильная(та что должна быть соответственно классу). fa-bookmark это сама иконка, fa-2x это ее размер, а fas и far закрашена или нет.https://fontawesome.com/icons/bookmark?style=solid  https://fontawesome.com/icons/bookmark?style=regular. Может я что-то не так понимаю..А если смотреть классы в elements в инструментах гуглхром, то класс динамически не меняется. Только когда открываешь статью заново.

2018-06-13 08:16 UTC, nLight commented on src/components/Article.vue
> +      return [this.article.readLater ? 'fas' : 'far', 'fa-bookmark', 'fa-2x']; //иконка меняется только после повторного открытия,а не динамически.this.article.readLater и класс меняется динамически.
Ага! Те. vue не перерисовывет ее на самом деле! В документации вроде нет примера, когда computed property возвращает массив. Есть только с объектом. Может в этом проблема? Я попробую запустить приложение, у меня не получалось найти rss потоки для теста :D может подскажешь сайты, которые ты используешь?

2018-06-14 08:01 UTC, di-shykh commented on src/components/Article.vue
> +      return [this.article.readLater ? 'fas' : 'far', 'fa-bookmark', 'fa-2x']; //иконка меняется только после повторного открытия,а не динамически.this.article.readLater и класс меняется динамически.
Хороший троллинг))Я же говорила,что первый парсер на jquery работал гораздо лучше,и сайты парсятся теперь все через раз-два.Не знаю почему.
Вот эти сайты, например
https://auto.onliner.by/feed
https://people.onliner.by/feed
https://news.tut.by/rss/world.rss
https://citydog.by/rss/
https://habr.com/rss/interesting/
Может и в этом. Я писала и просто v-bind:class="[this.article.readLater ? 'fas' : 'far', 'fa-bookmark', 'fa-2x']". В доках есть такой пример,та же ерунда.

2018-06-20 13:54 UTC, di-shykh commented on src/components/Article.vue
> +      if (source) this.$store.dispatch('userSources/saveCurrentSource', source);
Ты прав. У меня получилось не так, но отдельную статью получается теперь сохранять 
const articleRef = userDb.child(
      'sources/' + art.source.key + '/source/articles/' + art.article_key
    );
    const article = art.article;
    articleRef.set({
      title: article.title,
      link: article.link,
      description: article.description,
      date: article.date,
      img: article.img,
      read: article.read,
      readLater: article.readLater
    });
Не знаю правильно это или нет, но сохраняет как надо

2018-06-20 14:31 UTC, di-shykh commented on src/store/modules/appearance.js
> +    function changeContenttSize() {
Вроде как переписала это..но есть 2 косяка: 1)не работает в #app-content{overflow: auto;},2)съехал header, он не на всю ширину.Уже несколько дней мучаю эту ерунду,не понимаю, что не так. Отдельно сделала макетик, того как должно быть, там все норм(скинула архив тебе на почту), в проекте вроде как сделала все тоже самое, а вылезли эти косяки. Может увидишь свежим взглядом,что не так?

2018-06-20 15:25 UTC, nLight approved these changes

2018-06-20 15:45 UTC, merged